spring.application.name=billing-service

server.port=4001
grpc.server.port=9001

spring.datasource.url=jdbc:postgresql://localhost:5000/billing_db
spring.kafka.bootstrap-servers=localhost:9092
auth.service.url=http://localhost:4002